services:
    nginx_class_management:
        container_name: nginx_class_management
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./.docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/.htpasswd:/etc/nginx/.htpasswd
            - ./:/var/www/app
        depends_on:
            - app_class_management
        networks:
            - backend

    app_class_management:
        container_name: app_class_management
        restart: unless-stopped
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        command: ['php-fpm', '--nodaemonize']
        depends_on:
            - postgres_class_management
        working_dir: /var/www/app
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./:/var/www/app
        environment:
            UID: ${UID:-1000}
            GID: ${GID:-1001}
            CORS_ALLOW_ORIGIN: '*'
        networks:
            - backend

    postgres_class_management:
        container_name: postgres_class_management
        restart: unless-stopped
        image: postgres:15.1-alpine
        volumes:
            - ./.docker/postgresql:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - "5433:5432"
        networks:
            - backend

    pgadmin_class_management:
        container_name: pgadmin_class_management
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-glavvra4durki@gmail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
        ports:
            - '5050:80'

    redis_class_management:
        container_name: redis_class_management
        image: redis:alpine
        restart: unless-stopped
        environment:
            REDIS_PORT: ${REDIS_PORT:-6379}
            REDIS_DATABASES: ${REDIS_DATABASES:-16}
            REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
        volumes:
            - ./.docker/redis/data:/data
            - ./.docker/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - backend

    mailcatcher_class_management:
        container_name: mailcatcher_class_management
        image: dockage/mailcatcher:0.9.0
        restart: unless-stopped
        ports:
            - "1080:1080"
            - "1025:1025"

networks:
    backend:
