parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AdminBundle/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    admin.fundraising:
        class: App\AdminBundle\Admin\FundraisingAdmin
        calls:
            - setTranslationDomain: ['SonataAdminBundle']
        tags:
            - { name: sonata.admin, model_class: App\Entity\Fundraising, manager_type: orm, group: admin.group_management, label:  admin.child_fundraising, label_translator_strategy: sonata.admin.label.strategy.underscore }

    admin.contribution:
        class: App\AdminBundle\Admin\ContributionAdmin
        calls:
            - setTranslationDomain: ['SonataAdminBundle']
        tags:
            - { name: sonata.admin, model_class: App\Entity\Contribution, manager_type: orm, group: admin.group_management, label:  admin.child_contribution, label_translator_strategy: sonata.admin.label.strategy.underscore }

    admin.expenditure:
        class: App\AdminBundle\Admin\ExpenditureAdmin
        calls:
            -   setTranslationDomain: [ 'SonataAdminBundle' ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Expenditure, manager_type: orm, group: admin.group_management, label: admin.child_expenditure, label_translator_strategy: sonata.admin.label.strategy.underscore }

    admin.student:
        class: App\AdminBundle\Admin\StudentAdmin
        calls:
            - setTranslationDomain: ['SonataAdminBundle']
        tags:
            - { name: sonata.admin, model_class: App\Entity\Student, manager_type: orm, group: admin.group_management, label:  admin.child_student, label_translator_strategy: sonata.admin.label.strategy.underscore }
